version: '3.8'

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 song_lyric_handler.wsgi
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=song_lyric_handler.settings
      - SECRET_KEY=your_production_secret_key
      - DEBUG=False
      - ALLOWED_HOSTS=api.timesl.online,localhost,127.0.0.1

volumes:
  static_volume:
  media_volume: