version: '3.8'

services:
  web:
    secrets:
      - django_secret
    build: .
    command: gunicorn --bind 0.0.0.0:8000 song_lyric_handler.wsgi
    volumes:
      - static_volume:/app/staticfiles
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=song_lyric_handler.settings
      - SECRET_KEY_FILE=/run/secrets/django_secret
      - DEBUG=False
      - ALLOWED_HOSTS=api.timesl.online,localhost,127.0.0.1
secrets:
  django_secret:
    file: ./secrets/django_secret.txt

volumes:
  static_volume: