INSERT INTO
    songs (
        song_id,
        available,
        hidden,
        folder,
        art,
        artist,
        lyricist,
        title,
        subtitle,
        album,
        versions,
        is_duet,
        furigana,
        translation,
        updated_at,
        lang,
        credits
    )
VALUES
    (
        1408505419,
        1,
        NULL,
        'Mrs Green Apple, Sonoko Inoue - Tenbyouno Uta',
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ7NmbXHrqkonh23VACOzUY0JJjpRl1vKt75A&s',
        'Mrs. GREEN APPLE, Sonoko Inoue',
        '大森元貴',
        '点描の唄',
        NULL,
        '{"name": "Attitude", "link": "4NtJudb"}',
        '[{"version": "original", "id": "sL-yJIyuEaM", "default": true, "duration": "5:08"}]',
        1,
        0,
        '{"available": true, "author": "官方 YouTube 翻譯", "cite": "https://www.youtube.com/watch?v=rWsiVWlvw2E"}',
        '2025-06-08',
        'ja',
        '{"performance": [{"name": "大森元貴", "contribution": ["主唱", "吉他"]}, {"name": "Sonoko Inoue", "contribution": ["主唱"]}, {"name": "若井滉斗", "contribution": ["吉他"]}, {"name": "山中綾華", "contribution": ["鼓"]}, {"name": "藤澤涼架", "contribution": ["鋼琴"]}, {"name": "高野清宗", "contribution": ["低音吉他"]}], "song_writing": [{"name": "大森元貴", "contribution": ["詞曲創作", "編曲"]}], "engineering": [{"name": "Mrs. GREEN APPLE", "contribution": ["製作人"]}]}'
    ),
    (
        1445145789,
        1,
        NULL,
        'Mrs Green Apple - Bokuno Koto',
        'https://i.kfs.io/album/global/216180674,0v1/fit/500x500.jpg',
        'Mrs. GREEN APPLE',
        '大森元貴',
        '僕のこと',
        '大塚製薬「カロリーメイト」の新テレビCMソング',
        '{"name": "Attitude", "link": "4NtJudb"}',
        '[{"version": "original", "id": "xefpHEg5UIA", "default": true, "duration": "5:23"}]',
        0,
        0,
        '{"available": true, "author": "香榭"}',
        '2025-05-19',
        'ja',
        '{"performance": [{"name": "大森元貴", "contribution": ["主唱", "編程", "電吉他", "原聲吉他"]}, {"name": "若井滉斗", "contribution": ["電吉他"]}, {"name": "山中綾華", "contribution": ["鼓"]}, {"name": "藤澤涼架", "contribution": ["電子琴", "編程"]}, {"name": "高野清宗", "contribution": ["電子低音吉他"]}], "song_writing": [{"name": "大森元貴", "contribution": ["詞曲創作", "編曲"]}], "engineering": [{"name": "Mrs. GREEN APPLE", "contribution": ["製作人"]}]}'
    ),
    (
        1538265734,
        1,
        NULL,
        'Kenshi Yonezu - Campanella',
        'https://i.kfs.io/album/global/83019209,2v1/fit/500x500.jpg',
        '米津玄師',
        '米津玄師',
        'カンパネルラ',
        NULL,
        '{"name": "STRAY SHEEP", "link": "qvB12nv"}',
        '[{"version": "original", "id": "XeFQJ6-XoD0", "default": true, "duration": "4:14"}]',
        0,
        1,
        '{"available": true, "author": "Alice／箱庭博物館", "cite": "http://alicepika.blog.fc2.com/blog-entry-682.html", "modified": true}',
        '2025-05-15',
        'ja',
        '{"performance": [{"name": "米津玄師", "contribution": ["主唱", "吉他"]}, {"name": "須藤 優", "contribution": ["貝斯"]}], "song_writing": [{"name": "米津玄師", "contribution": ["詞曲創作", "編曲"]}, {"name": "Yuta Bandoh", "contribution": ["編曲"]}]}'
    ),
    (
        1629869580,
        1,
        NULL,
        'amazarashi - Cassiopeia Keiryuujo',
        'https://is1-ssl.mzstatic.com/image/thumb/Music122/v4/34/84/9c/34849ce0-673d-a17d-cac9-edc48bbbf959/4547366570427.jpg/1200x630bb.jpg',
        'amazarashi',
        '秋田ひろむ',
        'カシオピア係留所',
        '漫画「チ。」とのコラボ曲',
        '{"name": "永遠市", "link": "cCJ7CCq"}',
        '[{"version": "original", "id": "pTwSEgflLq0", "default": true, "duration": "6:23"}]',
        0,
        0,
        '{"available": true, "author": "Alice／箱庭博物館", "cite": "http://alicepika.blog.fc2.com/blog-entry-737.html"}',
        '2025-05-09',
        'ja',
        '{"performance": [{"name": "秋田ひろむ", "contribution": ["主唱"]}], "song_writing": [{"name": "秋田ひろむ", "contribution": ["詞曲創作"]}, {"name": "出羽良彰", "contribution": ["編曲"]}]}'
    ),
    (
        1646398286,
        1,
        NULL,
        'Kiro Akiyama - SKETCH',
        'https://lineimg.omusic.com.tw/img/album/6389351.jpg?v=20221007122445',
        '秋山黄色',
        'Kiro Akiyama',
        'SKETCH',
        'TVアニメ「僕のヒーローアカデミア」\n6期EDテーマ',
        '{"name": "Good Night Mare", "link": "43VsTEF"}',
        '[{"version": "original", "id": "M0cHair48Jg", "default": true, "duration": "4:16"}, {"version": "live", "id": "Y7IC9ccumcc", "duration": "4:10"}]',
        0,
        0,
        '{"available": true, "author": "香榭"}',
        '2025-05-01',
        'ja',
        '{"performance": [{"name": "Kiro Akiyama", "contribution": ["主唱"]}], "song_writing": [{"name": "Kiro Akiyama", "contribution": ["詞曲創作", "編曲"]}, {"name": "川口圭太", "contribution": ["編曲"]}]}'
    ),
    (
        1691229817,
        1,
        NULL,
        'Mrs Green Apple - Norn',
        'https://is1-ssl.mzstatic.com/image/thumb/Music116/v4/a4/ad/58/a4ad5816-0612-60d0-3ea2-917bea2e9c8e/23UMGIM61979.rgb.jpg/600x600bf-60.jpg',
        'Mrs. GREEN APPLE',
        '大森元貴, Marcus Lindberg',
        'Norn',
        NULL,
        '{"name": "Antenna", "link": "sR1MDAz"}',
        '[{"version": "original", "id": "9TqGIIVMigk", "default": true, "duration": "3:49"}]',
        0,
        NULL,
        '{"available": false, "author": "香榭"}',
        '2025-06-08',
        'se',
        '{"performance": [{"name": "大森元貴", "contribution": ["主唱", "吉他"]}, {"name": "若井滉斗", "contribution": ["曼陀林", "原聲吉他"]}, {"name": "藤澤涼架", "contribution": ["電子琴"]}, {"name": "Ryo Hanai", "contribution": ["編程"]}, {"name": "Ryo Kanda", "contribution": ["鼓"]}, {"name": "Natsuhiko Mori", "contribution": ["立式貝斯", "低音提琴"]}, {"name": "Anzu Suhara", "contribution": ["小提琴"]}, {"name": "吉田篤貴", "contribution": ["小提琴"]}, {"name": "Sumire Segawa", "contribution": ["中提琴"]}, {"name": "Kirin Uchida", "contribution": ["大提琴"]}, {"name": "Patri", "contribution": ["民間提琴"]}], "song_writing": [{"name": "大森元貴", "contribution": ["詞曲創作", "編曲"]}, {"name": "Ryo Hanai", "contribution": ["編曲"]}, {"name": "Marcus Lindberg", "contribution": ["翻譯"]}], "engineering": [{"name": "大森元貴", "contribution": ["製作人"]}, {"name": "Yoshinori Adachi", "contribution": ["混音師", "錄音師"]}]}'
    ),
    (
        1704107222,
        1,
        NULL,
        'Omoinotake - One Day',
        'https://is1-ssl.mzstatic.com/image/thumb/Music116/v4/66/15/63/6615632e-0049-f780-31b1-adcff2228853/4547366642797.jpg/600x600bf-60.jpg',
        'Omoinotake',
        '福島智朗',
        'One Day',
        NULL,
        '{"name": "Ammolite"}',
        '[{"version": "original", "id": "pOxWDTk7i1Y", "default": true, "duration": "3:46"}]',
        0,
        0,
        '{"available": true, "author": "官方 YouTube 翻譯", "cite":"https://www.youtube.com/watch?v=pOxWDTk7i1Y&t=50s&ab_channel=Omoinotake"}',
        '2025-06-20',
        'ja',
        '{"performance": [{"name": "Omoinotake", "contribution": ["混音師"]}, {"name": "Kohei Ishii", "contribution": ["混音師"]}], "song_writing": [{"name": "福島智朗", "contribution": ["作詞"]}, {"name": "藤井怜央", "contribution": ["作曲"]}, {"name": "Omoinotake", "contribution": ["編曲"]}, {"name": "Kohei Ishii", "contribution": ["編曲"]}]}'
    ),
    (
        1707027525,
        1,
        NULL,
        'Vaundy - Shiwaawase',
        'https://is1-ssl.mzstatic.com/image/thumb/Music126/v4/20/70/b3/2070b3d8-96d5-5e8b-1a4a-92a5e89f4b49/197189952913.jpg/600x600bf-60.jpg',
        'Vaundy',
        'Vaundy',
        'しわあわせ',
        '専門学校 首都医校、大阪医専、\n名古屋医専の2021年度TVCMソング',
        '{"name": "replica", "link": "UGs6ebR"}',
        '[{"version": "original", "id": "JwmGruvGt_I", "default": true, "duration": "4:43"}]',
        0,
        1,
        '{"available": true, "author": "995GOLDFISH", "cite": "https://www.995goldfish.com/2021/11/vaundy_22.html", "modified": true}',
        '2025-05-16',
        'ja',
        '{"performance": [{"name": "Vaundy", "contribution": ["主唱"]}], "song_writing": [{"name": "Vaundy", "contribution": ["詞曲創作", "編曲"]}]}'
    ),
    (
        1714599807,
        1,
        NULL,
        'Vaundy - replica',
        'https://i.kfs.io/album/global/263116610,3v1/fit/500x500.jpg',
        'Vaundy',
        'Vaundy',
        'replica',
        NULL,
        '{"name": "replica", "link": "UGs6ebR"}',
        '[{"version": "original", "id": "Uv67h_E7xsM", "default": true, "duration": "5:20"}]',
        0,
        0,
        '{"available": true, "author": "Oblivionis", "cite": "https://home.gamer.com.tw/artwork.php?sn=5830215"}',
        '2025-05-20',
        'ja',
        '{"performance": [{"name": "Vaundy", "contribution": ["主唱"]}], "song_writing": [{"name": "Vaundy", "contribution": ["詞曲創作", "編曲"]}]}'
    ),
    (
        1744861537,
        1,
        NULL,
        'HOYO-MiX, Chevy, Robin - Hope Is the Thing With Feathers',
        'https://is1-ssl.mzstatic.com/image/thumb/Music211/v4/d7/3c/d1/d73cd11f-5a83-60fd-c028-14241d6aa8be/198391981821.jpg/1200x630bb.jpg',
        'HOYO-MiX, Chevy, 知更鳥',
        'Ruby Qu、王可鑫',
        '希望有羽毛和翅膀',
        '《崩壞:星穹鐵道》匹諾康尼戰鬥主題曲',
        '{"name": "空氣蛹 - EP", "link": "xL9n1en"}',
        '[{"version": "original", "id": "m8VX1usnxlY", "default": true, "duration": "3:49"}, {"version": "instrumental", "id": "BPGF_w1p28U", "duration": "3:49"}, {"version": "live", "id": "ztCNc9CuKK8", "duration": "4:06"}]',
        0,
        NULL,
        '{"available": true, "author": "官方 YouTube 翻譯", "cite": "https://www.youtube.com/watch?v=pktTrSBAOJw&ab_channel=%E5%B4%A9%E5%A3%9E%3A%E6%98%9F%E7%A9%B9%E9%90%B5%E9%81%93"}',
        '2025-05-14',
        'en',
        '{"performance": [{"name": "知更鳥", "contribution": ["演出者"]}, {"name": "HOYO-MiX", "contribution": ["演出者"]}, {"name": "Chevy", "contribution": ["主唱"]}, {"name": "王可鑫", "contribution": ["演出者"]}], "song_writing": [{"name": "Ruby Qu", "contribution": ["作詞"]}, {"name": "王可鑫", "contribution": ["編曲", "詞曲創作"]}], "engineering": [{"name": "王可鑫", "contribution": ["製作人", "母帶工程師"]}, {"name": "阿烈", "contribution": ["混音師"]}, {"name": "宮奇", "contribution": ["母帶工程師"]}]}'
    ),
    (
        1758905748,
        1,
        NULL,
        'Vaundy - Gift',
        'https://is1-ssl.mzstatic.com/image/thumb/Music221/v4/e8/1f/49/e81f493c-1fca-8305-2664-25537206efe4/4547366698183.jpg/1200x1200bf-60.jpg',
        'Vaundy',
        'Vaundy',
        'Gift',
        '『僕のヒーローアカデミア\nTHE MOVIE ユアネクスト』ED主題歌',
        '{"name": "ホムンクルス/Gift"}',
        '[{"version": "original", "id": "sADskV54iNc", "default": true, "duration": "4:42"}]',
        0,
        0,
        '{"available": true, "author": "香榭"}',
        '2025-05-18',
        'ja',
        '{"performance": [{"name": "Vaundy", "contribution": ["主唱"]}], "song_writing": [{"name": "Vaundy", "contribution": ["詞曲創作", "編曲"]}]}'
    ),
    (
        1809714969,
        1,
        NULL,
        'HOYO-MiX, Vision Wei, Nea - On the Journey',
        'https://lineimg.omusic.com.tw/img/album/7690376.jpg?v=20250428143032',
        'HOYO-MiX, 魏晨, Nea',
        'Ruby Qu、王可鑫',
        '不虛此行',
        '《崩壞:星穹鐵道》兩週年紀念曲',
        NULL,
        '[{"version": "original", "id": "0WyDtxRZ938", "default": true, "duration": "2:37"}, {"version": "instrumental", "id": "YOWLfsIHkZg", "duration": "2:37"}]',
        1,
        NULL,
        '{"available": true, "author": "官方 YouTube 翻譯", "cite": "https://www.youtube.com/watch?v=GdBLXGUy2C0&pp=ygUM5LiN6Jmb5q2k6KGM"}',
        '2025-05-09',
        'en',
        '{"performance": [{"name": "HOYO-MiX", "contribution": ["演出者"]}, {"name": "魏晨", "contribution": ["主唱"]}, {"name": "NEA", "contribution": ["主唱"]}], "song_writing": [{"name": "王可鑫", "contribution": ["詞曲創作", "編曲"]}, {"name": "Ruby Qu", "contribution": ["作詞"]}], "engineering": [{"name": "崔瀚普", "contribution": ["製作人"]}, {"name": "张迦南", "contribution": ["母帶工程師"]}, {"name": "王可鑫", "contribution": ["製作人", "母帶工程師"]}, {"name": "阿烈", "contribution": ["混音師"]}]}'
    )